[tool.isort]
profile = "black"
force_to_top = "typing"
from_first = true
combine_as_imports = true
line_length = 99

[tool.black]
line-length = 99
target-version = ["py310"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
addopts = "--ignore mautrix/util/db/ --ignore mautrix/bridge/"
